"""Pydantic request and response schemas for the VulScanner API."""

from app.schemas.auth import (
    LoginRequest,
    PasswordChangeRequest,
    TokenPair,
    UserCreate,
    UserOut,
    UserUpdate,
)
from app.schemas.common import Message, Page, ScanProfileInfo
from app.schemas.scan import (
    ScanCreate,
    ScanDetail,
    ScanOut,
    ScanProgressEvent,
    ScanResultOut,
)
from app.schemas.security import (
    AssetOut,
    AuditLogOut,
    DashboardSummary,
    FindingOut,
    FindingUpdate,
    NetworkHostOut,
    NetworkPortOut,
    RemediationOut,
    ReportCreate,
    ReportOut,
    TargetCreate,
    TargetOut,
    TopologyOut,
    VulnerabilityOut,
)

__all__ = [
    "AssetOut",
    "AuditLogOut",
    "DashboardSummary",
    "FindingOut",
    "FindingUpdate",
    "LoginRequest",
    "Message",
    "NetworkHostOut",
    "NetworkPortOut",
    "Page",
    "PasswordChangeRequest",
    "RemediationOut",
    "ReportCreate",
    "ReportOut",
    "ScanCreate",
    "ScanDetail",
    "ScanOut",
    "ScanProfileInfo",
    "ScanProgressEvent",
    "ScanResultOut",
    "TargetCreate",
    "TargetOut",
    "TokenPair",
    "TopologyOut",
    "UserCreate",
    "UserOut",
    "UserUpdate",
    "VulnerabilityOut",
]
