"""Initial VulScanner schema

Revision ID: 8b8d1a0bbee0
Revises: 
Create Date: 2026-08-15 18:34:32.608405
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types  # custom JSON column types used by the models


revision: str = '8b8d1a0bbee0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_vector', sa.String(length=128), nullable=True),
    sa.Column('cvss_v2_score', sa.Float(), nullable=True),
    sa.Column('cvss_severity', sa.String(length=16), nullable=True),
    sa.Column('attack_vector', sa.String(length=24), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('cwe_ids', app.db.types.JSONList(), nullable=False),
    sa.Column('cpe_matches', app.db.types.JSONList(), nullable=False),
    sa.Column('references', app.db.types.JSONList(), nullable=False),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('kev_date_added', sa.String(length=32), nullable=True),
    sa.Column('kev_due_date', sa.String(length=32), nullable=True),
    sa.Column('kev_ransomware', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cves'))
    )
    with op.batch_alter_table('cves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cves_cve_id'), ['cve_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cves_kev'), ['kev'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', app.db.types.JSONMap(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('authorization_note', sa.Text(), nullable=False),
    sa.Column('authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], name=op.f('fk_targets_authorized_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_value'), ['value'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_uid', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('fqdn', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('ip_addresses', app.db.types.JSONList(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('os_name', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('os_build', sa.String(length=32), nullable=True),
    sa.Column('os_edition', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('os_confidence', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False),
    sa.Column('open_port_count', sa.Integer(), nullable=False),
    sa.Column('labels', app.db.types.JSONMap(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_assets_target_id_targets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_uid'), ['asset_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index('ix_assets_ip_mac', ['ip_address', 'mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_mac_address'), ['mac_address'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('profile', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('options', app.db.types.JSONMap(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('stages', app.db.types.JSONList(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('scanner_version', sa.String(length=32), nullable=False),
    sa.Column('scanner_host', sa.String(length=255), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('asset_count', sa.Integer(), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False),
    sa.Column('warnings', app.db.types.JSONList(), nullable=False),
    sa.Column('errors', app.db.types.JSONList(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scans_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_scans_target_id_targets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_target'), ['target'], unique=False)

    op.create_table('network_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('local_address', sa.String(length=45), nullable=False),
    sa.Column('local_port', sa.Integer(), nullable=True),
    sa.Column('remote_address', sa.String(length=45), nullable=True),
    sa.Column('remote_port', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=128), nullable=True),
    sa.Column('remote_scope', sa.String(length=16), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_network_connections_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_network_connections_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_connections'))
    )
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_connections_scan_id'), ['scan_id'], unique=False)

    op.create_table('network_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node', sa.String(length=128), nullable=False),
    sa.Column('target_node', sa.String(length=128), nullable=False),
    sa.Column('edge_type', sa.String(length=24), nullable=False),
    sa.Column('relationship_confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence', app.db.types.JSONMap(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_network_edges_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_edges'))
    )
    with op.batch_alter_table('network_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_edges_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_edges_source_node'), ['source_node'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_edges_target_node'), ['target_node'], unique=False)

    op.create_table('network_hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('discovery_method', sa.String(length=32), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('os_guess', sa.String(length=128), nullable=True),
    sa.Column('os_confidence', sa.String(length=16), nullable=False),
    sa.Column('os_evidence', app.db.types.JSONList(), nullable=False),
    sa.Column('is_gateway', sa.Boolean(), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_network_hosts_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_network_hosts_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_hosts'))
    )
    with op.batch_alter_table('network_hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_hosts_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_hosts_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_hosts_scan_id'), ['scan_id'], unique=False)

    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('installed_on', sa.String(length=32), nullable=True),
    sa.Column('installed_by', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('evidence', app.db.types.JSONMap(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_patches_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_patches_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patches'))
    )
    with op.batch_alter_table('patches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patches_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patches_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patches_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patches_state'), ['state'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', app.db.types.JSONMap(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_reports_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_scan_id'), ['scan_id'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('collector', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data', app.db.types.JSONMap(), nullable=False),
    sa.Column('warnings', app.db.types.JSONList(), nullable=False),
    sa.Column('errors', app.db.types.JSONList(), nullable=False),
    sa.Column('collection_method', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_scan_results_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_results_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_results'))
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_results_collector'), ['collector'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_scan_id'), ['scan_id'], unique=False)

    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('cve_ref_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('product_version', sa.String(length=64), nullable=False),
    sa.Column('affected_versions', sa.String(length=255), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', app.db.types.JSONMap(), nullable=False),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('evidence', app.db.types.JSONMap(), nullable=False),
    sa.Column('patch', sa.String(length=255), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('references', app.db.types.JSONList(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_vulnerabilities_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cve_ref_id'], ['cves.id'], name=op.f('fk_vulnerabilities_cve_ref_id_cves'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_vulnerabilities_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities')),
    sa.UniqueConstraint('scan_id', 'asset_id', 'cve_id', 'product', 'product_version', name='uq_vuln_scope')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_kev'), ['kev'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_uid', sa.String(length=48), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('evidence', app.db.types.JSONMap(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('detection_method', sa.String(length=128), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('remediation_command', sa.Text(), nullable=False),
    sa.Column('references', app.db.types.JSONList(), nullable=False),
    sa.Column('risk_factors', app.db.types.JSONMap(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('scan_result_id', sa.Integer(), nullable=True),
    sa.Column('vulnerability_id', sa.Integer(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_note', sa.Text(), nullable=False),
    sa.Column('status_changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_findings_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], name=op.f('fk_findings_scan_result_id_scan_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_changed_by_id'], ['users.id'], name=op.f('fk_findings_status_changed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_findings_vulnerability_id_vulnerabilities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_finding_uid'), ['finding_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('network_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('service_source', sa.String(length=24), nullable=False),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('local_address', sa.String(length=45), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=128), nullable=True),
    sa.Column('process_path', sa.Text(), nullable=True),
    sa.Column('owning_service', sa.String(length=128), nullable=True),
    sa.Column('exposure', sa.String(length=24), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_network_ports_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['network_hosts.id'], name=op.f('fk_network_ports_host_id_network_hosts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_network_ports_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_ports'))
    )
    with op.batch_alter_table('network_ports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_ports_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ports_port'), ['port'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_ports_scan_id'), ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_ports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_ports_scan_id'))
        batch_op.drop_index(batch_op.f('ix_network_ports_port'))
        batch_op.drop_index(batch_op.f('ix_network_ports_asset_id'))

    op.drop_table('network_ports')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_findings_finding_uid'))
        batch_op.drop_index(batch_op.f('ix_findings_category'))
        batch_op.drop_index(batch_op.f('ix_findings_asset_id'))

    op.drop_table('findings')
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_status'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_severity'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_scan_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_kev'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_cve_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_asset_id'))

    op.drop_table('vulnerabilities')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_results_scan_id'))
        batch_op.drop_index(batch_op.f('ix_scan_results_collector'))

    op.drop_table('scan_results')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_scan_id'))
        batch_op.drop_index(batch_op.f('ix_reports_format'))

    op.drop_table('reports')
    with op.batch_alter_table('patches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patches_state'))
        batch_op.drop_index(batch_op.f('ix_patches_scan_id'))
        batch_op.drop_index(batch_op.f('ix_patches_kb_id'))
        batch_op.drop_index(batch_op.f('ix_patches_asset_id'))

    op.drop_table('patches')
    with op.batch_alter_table('network_hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_hosts_scan_id'))
        batch_op.drop_index(batch_op.f('ix_network_hosts_mac_address'))
        batch_op.drop_index(batch_op.f('ix_network_hosts_ip_address'))

    op.drop_table('network_hosts')
    with op.batch_alter_table('network_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_edges_target_node'))
        batch_op.drop_index(batch_op.f('ix_network_edges_source_node'))
        batch_op.drop_index(batch_op.f('ix_network_edges_scan_id'))

    op.drop_table('network_edges')
    with op.batch_alter_table('network_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_connections_scan_id'))

    op.drop_table('network_connections')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_target'))
        batch_op.drop_index(batch_op.f('ix_scans_status'))

    op.drop_table('scans')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_mac_address'))
        batch_op.drop_index(batch_op.f('ix_assets_last_seen'))
        batch_op.drop_index('ix_assets_ip_mac')
        batch_op.drop_index(batch_op.f('ix_assets_ip_address'))
        batch_op.drop_index(batch_op.f('ix_assets_hostname'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_uid'))

    op.drop_table('assets')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_value'))
        batch_op.drop_index(batch_op.f('ix_targets_target_type'))

    op.drop_table('targets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('cves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cves_kev'))
        batch_op.drop_index(batch_op.f('ix_cves_cve_id'))

    op.drop_table('cves')
    # ### end Alembic commands ###
